import type { Metadata } from "next";
import { DocsPage, CodeBlock, Section, Note } from "@/components/docs-page";

export const metadata: Metadata = { title: "GitHub Issues" };

export default function GitHubIssuesPage() {
  return (
    <DocsPage
      title="GitHub Issues"
      description="Auto-spawn agents from GitHub issue events — labels, assignments, and state changes."
    >
      <Section title="How it works">
        <p>
          A GitHub Issues workflow watches webhook events from your repositories.
          When an issue matches your trigger conditions, ElasticClaw creates an agent
          pre-loaded with the issue context. The agent implements the fix/feature,
          opens a PR, and signals done with <code className="text-cyan-300">[DONE]</code>.
        </p>
        <p>Trigger conditions:</p>
        <ul className="list-disc list-inside space-y-1 text-sm text-zinc-400">
          <li>Issue state changes to <code>open</code> (or a configured label is applied)</li>
          <li>All configured <code>labels</code> are present on the issue (AND)</li>
          <li><code>assigned_to</code> filter matches (if configured)</li>
        </ul>
        <p className="mt-2 text-sm text-zinc-400">
          This page assumes you already have a workspace, such as{" "}
          <code>my-app</code>. Add the issue tracker to that workspace, then
          publish workflow YAML into it.
        </p>
      </Section>

      <Section title="1. Configure the issue tracker">
        <CodeBlock lang="text">{`Settings -> Workspaces -> my-app -> Issue Trackers
Add GitHub Issues:
  token: ghp_xxxxxxxxxxxxx
  webhook secret: generated by ElasticClaw Server`}</CodeBlock>
        <p className="text-sm text-zinc-400 mt-2">
          The token needs <code>repo</code> scope for private repos or <code>public_repo</code>
          for public repos. The webhook secret is stored in the selected workspace
          and validates incoming webhooks via HMAC-SHA256.
        </p>
      </Section>

      <Section title="2. Set up the webhook">
        <p>In your GitHub repository settings:</p>
        <ol className="list-decimal list-inside space-y-2 text-sm text-zinc-400">
          <li>Go to <strong>Settings → Webhooks → Add webhook</strong></li>
          <li>Payload URL: <code>https://server.example.com/api/workspaces/my-app/webhooks/github-issues</code></li>
          <li>Content type: <code>application/json</code></li>
          <li>Secret: your webhook secret</li>
          <li>Events: <strong>Issues</strong></li>
        </ol>
      </Section>

      <Section title="3. Create a workflow">
        <p>
          Create a workflow YAML file for your repository, labels, and lifecycle stages:
        </p>
        <CodeBlock lang="yaml">{`# .elasticclaw/workflows/bugfix-bot.yaml
schema_version: v1
name: bugfix-bot
trigger:
  github_issues:
    event: issue_labeled
    repositories:
      - my-org/my-app
    states:
      - open
    labels:
      - agent-ready
    labelers:
      - "*"

stages:
  - id: working
    label: Working
    entry: true
    on_enter:
      remove_labels: [agent-ready]
      add_labels: [agent-working]
      inject: |
        Issue: {{.Issue.Identifier}} — {{.Issue.Title}}
        URL: {{.Issue.URL}}

        Read CONTEXT.md and start working.

  - id: pr_opened
    label: PR Opened
    triggers:
      - message_contains: "[DONE]"
    on_enter:
      add_labels: [in-review]
      remove_labels: [agent-working]

  - id: merged
    label: Merged
    triggers:
      - pr_merged: {}
    terminal: true`}</CodeBlock>
        <Note>
          GitHub Issues workflows can use <code>stages</code> to add and remove
          labels, inject messages, and terminate when the tracked PR merges.
        </Note>
      </Section>

      <Section title="4. Push the workflow">
        <CodeBlock lang="bash">{`elasticclaw workflow push --workspace my-app .elasticclaw/workflows/bugfix-bot.yaml`}</CodeBlock>
      </Section>

      <Section title="Template variables">
        <p className="text-sm text-zinc-400">
          In <code>stages[].on_enter.inject</code>, automatic GitHub Issues
          workflows expose this complete issue object:
        </p>
        <div className="space-y-2 text-sm text-zinc-400 mt-2">
          <p><code className="text-cyan-300">{"{{.Issue.Identifier}}"}</code> — Issue number as <code>#42</code>.</p>
          <p><code className="text-cyan-300">{"{{.Issue.Title}}"}</code> — GitHub issue title.</p>
          <p><code className="text-cyan-300">{"{{.Issue.URL}}"}</code> — Browser URL for the issue.</p>
          <p><code className="text-cyan-300">{"{{.Issue.Description}}"}</code> — GitHub issue body.</p>
        </div>
      </Section>

      <Section title="Filters">
        <h3 className="text-sm font-semibold text-zinc-200 mt-4 mb-2">Labels</h3>
        <p className="text-sm text-zinc-400">
          All configured labels must be present on the issue. The trigger also fires when
          a label is <em>added</em> to an already-open issue (if the label completes the set).
        </p>

        <h3 className="text-sm font-semibold text-zinc-200 mt-4 mb-2">AssignedTo</h3>
        <p className="text-sm text-zinc-400">
          Filter by assignee:
        </p>
        <ul className="list-disc list-inside space-y-1 text-sm text-zinc-400">
          <li><code>@username</code> — only this user</li>
          <li><code>!@username</code> — exclude this user</li>
          <li><code>any</code> — must have an assignee</li>
          <li><code>none</code> — must be unassigned</li>
        </ul>
      </Section>

      <Section title="Context file">
        <p className="text-sm text-zinc-400">
          When an agent is created, ElasticClaw Server writes a <code>CONTEXT.md</code> file containing
          the issue title, description, labels, author, and instructions. The agent reads this
          on startup to understand its task.
        </p>
      </Section>

      <Note>
        GitHub Issues workflows support the same stages as Linear/Shortcut workflows.
        The default workflow can move the issue on <code>[DONE]</code>
        and terminates when the PR merges or closes.
      </Note>
    </DocsPage>
  );
}
